In [3]:
import numpy as np # linear algebra
np.random.seed(10)
import pandas as pd # data processing, CSV file I/O (e.g., pd.read_csv

import matplotlib.pyplot as plt
import seaborn as sns
# Required magic to display matplotlib plots in notebooks
%matplotlib inline
#reading the files 
data_train = pd.read_csv('tested.csv')

In [5]:
data_train.head(8)


PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   
5          897         0       3   
6          898         1       3   
7          899         0       2   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
5                    Svensson, Mr. Johan Cervin    male  14.0      0      0   
6                          Connolly, Miss. Kate  female  30.0      0      0   
7                  Caldwell, Mr. Albert Francis    male  26.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S  
5     7538   9.2250   NaN        S  
6   330972   7.6292   NaN        Q  
7   248738  29.0000   NaN        S

In [6]:
# We define a dictionary to transform the 0,1 values in the 
# labels to a String that defines the fate of the passenger
dict_live = {
 0 : 'Perished',
 1 : 'Survived'
}

In [7]:
 # We define a dictionary to assign labels 0 or 1
# corresponding to the sex
dict_sex = {
 'male' : 0,
 'female' : 1
}

In [8]:
 #We apply the dictionary using a lambda function and the pandas .apply

data_train['BSex'] = data_train['Sex'].apply(lambda x: dict_sex[x])
#This line displasy the dataframe with the new column
data_train.head()


PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  BSex  
0   330911   7.8292   NaN        Q     0  
1   363272   7.0000   NaN        S     1  
2   240276   9.6875   NaN        Q     0  
3   315154   8.6625   NaN        S     0  
4  3101298  12.2875   NaN        S     1

In [9]:
features = data_train[['Pclass', 'BSex']].to_numpy()
print(features)

[[3 0]
 [3 1]
 [2 0]
 [3 0]
 [3 1]
 [3 0]
 [3 1]
 [2 0]
 [3 1]
 [3 0]
 [3 0]
 [1 0]
 [1 1]
 [2 0]
 [1 1]
 [2 1]
 [2 0]
 [3 0]
 [3 1]
 [3 1]
 [1 0]
 [3 0]
 [1 1]
 [1 0]
 [1 1]
 [3 0]
 [1 1]
 [3 0]
 [1 0]
 [3 0]
 [2 0]
 [2 0]
 [3 1]
 [3 1]
 [1 0]
 [3 0]
 [3 1]
 [3 1]
 [3 0]
 [3 0]
 [3 0]
 [1 0]
 [3 0]
 [2 1]
 [1 1]
 [3 0]
 [1 0]
 [3 0]
 [1 1]
 [3 1]
 [1 0]
 [2 0]
 [2 1]
 [1 1]
 [2 0]
 [3 0]
 [3 0]
 [3 0]
 [3 0]
 [1 1]
 [3 0]
 [2 0]
 [3 0]
 [3 1]
 [1 0]
 [2 1]
 [3 1]
 [1 0]
 [1 0]
 [1 1]
 [3 1]
 [3 0]
 [3 1]
 [1 0]
 [1 1]
 [1 0]
 [3 0]
 [1 1]
 [2 0]
 [3 1]
 [3 0]
 [1 0]
 [1 0]
 [3 0]
 [2 0]
 [3 0]
 [3 1]
 [3 1]
 [3 1]
 [2 0]
 [3 1]
 [3 0]
 [1 1]
 [3 0]
 [1 0]
 [3 0]
 [1 1]
 [3 0]
 [3 1]
 [3 0]
 [1 1]
 [2 0]
 [3 0]
 [3 0]
 [3 1]
 [3 0]
 [3 0]
 [3 0]
 [3 0]
 [2 0]
 [2 0]
 [3 1]
 [1 1]
 [3 1]
 [1 1]
 [3 0]
 [3 0]
 [3 1]
 [1 0]
 [2 1]
 [2 1]
 [3 0]
 [1 1]
 [3 0]
 [3 0]
 [3 1]
 [3 0]
 [3 1]
 [2 0]
 [3 0]
 [3 0]
 [1 0]
 [3 1]
 [3 0]
 [3 0]
 [3 0]
 [3 0]
 [2 0]
 [3 1]
 [3 0]
 [3 1]
 [1 1]
 [1 0]

In [11]:
#Define the sigmoid activator
def sigmoid_act(z):
 # sigmoid
 a = 1/(1+ np.exp(-z))
 return a

In [13]:
# We may employ the Rectifier Linear Unit (ReLU)
def ReLU_act(z):
  return max(0, z)

In [14]:
def perceptron(X, act):
 np.random.seed(1) #seed for reproducibilty
 shapes = X.shape #get the number of (rows, columns)
 n = shapes[0] + shapes[1] #adding the number of rows and colums
 # Generating random weights and bias
 w = 2*np.random.random(shapes) - 0.5 #we want initial w between -1 and 1
 w_0 = np.random.random(1)
 # Initialize the function
 f = w_0[0]
 for i in range(0, X.shape[0]-1): #run over column elements
   for j in range(0, X.shape[1]-1): #run over rows elements
     f += w[i, j]*X[i,j]/n #adding each component of input multiplied by corresponding weight
 # Pass it to the activation function and return it as an output
 if act == 'Sigmoid':
   output = sigmoid_act(f)
 elif act == "ReLU":
   output = ReLU_act(f)
 return output

In [17]:
print('Output with sigmoid activator: ', perceptron(features, act = 'Sigmoid'))

Output with sigmoid activator:  0.7881557564071333


In [18]:
print('Output with ReLU activator: ', perceptron(features, act = "ReLU"))

Output with ReLU activator:  1.3138444261267481


In [19]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [20]:
# Load the iris dataset
iris = datasets.load_iris()
# Create our X and y data
X = iris.data
y = iris.target

In [21]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [22]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
# Split the data into 75% training data and 25% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
X_train.shape, X_test.shape

((112, 4), (38, 4))

In [24]:
sc = StandardScaler()
sc.fit(X_train)

StandardScaler()

In [25]:
 # Apply the scaler to the X training data
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [26]:
 # Create a perceptron object with the parameters:max_ieter (epochs) equal to 40 learning rate of 0.1
ppn = Perceptron(max_iter = 1000, eta0 = 0.1, random_state = 0)
# Train the perceptron
ppn.fit(X_train_std, y_train)

Perceptron(eta0=0.1)

In [27]:
 # Apply the trained perceptron on the X data to make predicts for they test dat
y_pred = ppn.predict(X_test_std)
y_pred

array([2, 1, 0, 2, 1, 0, 1, 2, 0, 0, 2, 2, 0, 0, 1, 2, 0, 1, 1, 2, 1, 2,
       0, 0, 1, 0, 0, 1, 1, 0, 2, 2, 1, 1, 1, 1, 0, 0])

In [29]:
y_pred

array([2, 1, 0, 2, 1, 0, 1, 2, 0, 0, 2, 2, 0, 0, 1, 2, 0, 1, 1, 2, 1, 2,
       0, 0, 1, 0, 0, 1, 1, 0, 2, 2, 1, 1, 1, 1, 0, 0])

In [30]:
y_test

array([2, 1, 0, 2, 2, 0, 1, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 1, 1, 2, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 1, 2, 0, 0])

In [31]:
 # View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.87


In [32]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
mlp.fit(X_train_std, y_train)

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [33]:
mlp_y_pred = mlp.predict(X_test_std)
mlp_y_pred

array([2, 1, 1, 2, 2, 0, 1, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 1, 1, 2, 1, 2,
       0, 0, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 1, 2, 0, 0])

In [34]:
 # View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, mlp_y_pred))

Accuracy: 0.95
